In [21]:
import pandas as pd
import numpy as np
df = pd.read_csv('csv_result-Amostras_Treinamento_WV_3_Nivel_1_Arff.csv')
df

id      SAVI    NDVI_4    NDVI_3    NDVI_2    NDVI_1  A_Bri_Todas  \
0      1  0.445056  0.151780  0.381752  0.056918  0.296909   158.472067   
1      2 -0.201749 -0.163363 -0.138499 -0.159447 -0.134553    -2.389007   
2      3 -0.027614 -0.110212  0.006475 -0.134734 -0.018419     1.178177   
3      4  0.256585  0.051272  0.255617 -0.037182  0.171195    50.670838   
4      5  0.239442  0.036465  0.226924 -0.033319  0.159751     7.272871   
..   ...       ...       ...       ...       ...       ...          ...   
508  509  0.462411  0.130957  0.368886  0.063190  0.308326   876.814209   
509  510  0.532200  0.151068  0.411439  0.085665  0.354852   796.499753   
510  511  0.546539  0.173273  0.418253  0.110971  0.364412   864.732286   
511  512  0.516244  0.150201  0.398731  0.087837  0.344207  1000.501483   
512  513  0.990017  0.244157  0.692092  0.187963  0.660103   774.878394   

         AC_9      AC_8      AC_7  ...   'Mean.40     'Mean.41     'Mean.42  \
0    0.447438  0.892295  0.542128  ...  -8.169620   199.127815   223.031003   
1    1.321530  1.379386  1.310946  ... -11.467251     0.063633     0.090360   
2    0.987133  1.311429  1.037530  ... -10.633529     0.355530     0.726843   
3    0.592842  1.077235  0.707658  ... -12.376023    38.611830    54.739680   
4    0.630093  1.068935  0.724508  ...  -3.468881     0.000000     1.638002   
..        ...       ...       ...  ...        ...          ...          ...   
508  0.461042  0.881132  0.528671  ...   1.829424  1180.028152  1368.848225   
509  0.416994  0.842189  0.476176  ...   0.198680  1048.631621  1207.460211   
510  0.410185  0.800227  0.465833  ...   0.616802  1097.614206  1268.228412   
511  0.429868  0.838511  0.487866  ...  -3.632927  1336.958797  1524.104415   
512  0.181969  0.683553  0.204745  ...   4.858285   909.745679  1097.259259   

        'Mean.43     'Mean.44     'Mean.45     'Mean.46     'Mean.47  \
0     196.721556   204.887833   404.742615   505.544019   294.344838   
1       0.000000     0.030544     0.383073     0.519249     0.132358   
2       0.744457     0.542586     2.861286     4.405111     2.482221   
3      31.984904    30.775724   127.880776   180.032039    88.176217   
4       0.000000     0.000000     6.617527    22.355446     6.093366   
..           ...          ...          ...          ...          ...   
508  1560.468788  1540.471236  2129.552020  2322.363525  2039.137087   
509  1367.710935  1344.028063  1902.272200  2087.986430  1852.730171   
510  1487.977020  1451.016017  2100.078691  2375.559889  2052.430362   
511  1758.364894  1725.430293  2397.351904  2622.893889  2355.546181   
512  1230.696296  1212.214815  1892.498765  2111.669136  1827.096296   

       'Mean.48              'Class  
0    -15.065224              Sombra  
1    141.579065                Lago  
2     65.499723                Lago  
3    -25.103820                Lago  
4    -10.208845                Lago  
..          ...                 ...  
508   21.113831  Vegetacao Rasteira  
509   48.006061  Vegetacao Rasteira  
510   34.426184  Vegetacao Rasteira  
511   98.779519  Vegetacao Rasteira  
512  -75.187654  Vegetacao Rasteira  

[513 rows x 125 columns]

In [65]:
x = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

In [27]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.25, random_state = 0)

In [28]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [61]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 1000, criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=1000, random_state=0)

In [62]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[['Coberturas_Metalicas' 'Coberturas_Metalicas']
 ['Solo Exposto' 'Solo Exposto']
 ['Diversas' 'Diversas']
 ['Diversas' 'Diversas']
 ['Diversas' 'Diversas']
 ['Diversas' 'Diversas']
 ['Diversas' 'Diversas']
 ['Diversas' 'Diversas']
 ['Diversas' 'Diversas']
 ['Diversas' 'Diversas']
 ['Diversas' 'Diversas']
 ['Diversas' 'Diversas']
 ['Coberturas_Metalicas' 'Coberturas_Metalicas']
 ['Vegetacao Arborea' 'Vegetacao Arborea']
 ['Piscina' 'Piscina']
 ['Piscina' 'Piscina']
 ['Coberturas_Metalicas' 'Coberturas_Metalicas']
 ['Diversas' 'Diversas']
 ['Diversas' 'Diversas']
 ['Diversas' 'Diversas']
 ['Coberturas_Metalicas' 'Coberturas_Metalicas']
 ['Pav_Viaria' 'Pav_Viaria']
 ['Coberturas_Metalicas' 'Coberturas_Metalicas']
 ['Coberturas_Metalicas' 'Coberturas_Metalicas']
 ['Diversas' 'Diversas']
 ['Diversas' 'Diversas']
 ['Diversas' 'Diversas']
 ['Coberturas_Metalicas' 'Coberturas_Metalicas']
 ['Pav_Viaria' 'Pav_Viaria']
 ['Coberturas_Metalicas' 'Coberturas_Metalicas']
 ['Coberturas_Metalicas' 'Co

In [63]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[ 2  0  0  0  0  0  0  0  0  0  0]
 [ 0 33  2  0  0  0  0  0  0  0  0]
 [ 0  0 45  0  0  0  0  0  0  0  0]
 [ 0  0  0  1  0  0  0  0  0  0  0]
 [ 0  0  4  0 14  0  0  0  0  0  0]
 [ 0  0  0  0  0  4  0  0  0  0  0]
 [ 0  1  0  0  0  0  5  0  0  0  0]
 [ 0  0  0  0  0  0  0  3  0  0  0]
 [ 0  0  0  0  0  0  0  0  6  0  0]
 [ 0  0  0  0  0  0  0  0  0  4  0]
 [ 0  0  0  0  0  0  0  0  0  0  5]]


In [64]:
accuracy_score(y_test, y_pred)

0.9457364341085271